---
title: "GIS And Remote Sensing For Ecologists"
author: "Emilio Berti"
date: "`r Sys.Date()`"
site: "bookdown::bookdown_site"
output: bookdown::bs4_book
documentclass: book
citation_package: natbib
bibliography: ["book.bib", "packages.bib"]
biblio-style: apalike
link-citations: yes
---

# Preface {-}

I started learning GIS in 2017 during my PhD.
I first approached GIS using ArcGIS, which I hated with all my guts.
As I prefer typing on terminal rather than clicking on icons, I quickly switched to R.
I will use the R package `terra` thorough this course.
You can replicate most of the content of this course using python, but I will leave that for another time.
This course is intended for newcomers to GIS; experienced users should definitely look somewhere else (most likely on [stackoverflow.com](https://stackoverflow.com)).

The course is divided into three main parts:

  1. General introduction to GIS.
  2. Fundamentals for GIS analysis.
  3. GIS analysis with Google Earth Engine.

In the first part of this course, I will introduce the basic concepts of GIS using R.
In the second part, I will cover the fundamentals of GIS analysis.
I will explain the theory behind it and complement it with examples from actual analyses, introducing the most common workflows in R.
In the third part, I will focus on Google Earth Engine and explain how to move heavy GIS analyses on the cloud.
This will require a basic understanding of JavaScript.
It would be great to talk about how to interface with Google Earth Engine using python, but this topic is probably too advanced and will be the focus of another course.

## Software requirements {-}

To install all packages and modules used in this book, you can use the [conda](https://docs.conda.io/en/latest) environment management system.
The environment file is at [https://github.com/emilio-berti/gis-course/blob/master/conda/gis-course.yml](https://github.com/emilio-berti/gis-course/conda/gis-course.yml).

```bash
conda env create --file=gis-course.yml
```

```{r setup, echo=FALSE, message=FALSE}
library(terra)
```
